### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by fuglede** [lovasoa/highs-js#12]
Great project; I can see how this fits a number of use cases that no preexisting tools could handle!

Would it be possible to put a few words -- maybe just in the `README.md` -- on any potential gotchas imposed by going through Emscripten/Wasm? I'm thinking things like being limited to 32-bit addressing (and 2 GB memory pages), only being able to use parallel being limited to Chrome (if that's even a thing?), and any other potential pitfalls in using this over just using the HiGHS CLI?

**Comment by lovasoa** [comment]
I am not particularly knowledgeable on the topic, but feel free to run experiments and contribute to the readme !

**Comment by fuglede** [comment]
Noted; thanks! I might just do that; the main experiment I can think of would be to see what handles for problems where HiGHS would use more than 2 GB of memory.

I realize that as stated, the issue doesn't really have much in terms of a well-defined objective, so let me just close it to avoid littering (and do feel free to re-open if that makes more sense).
