### ISSUE TITLE
Since latest update, Highs returns "unable to read LP model" while the error should be "infeasible problem"

### ISSUE THREAD

**Issue by lequant40** [lovasoa/highs-js#17]
Hello,

As per issue title.

Reproducer:

Minimize
 obj: x1
Subject To
 c1: 1 x0 1 x1 = 1
Bounds
 0 <= x1 <= 1
 1.1 <= x2 <= 1
End
     
This now results in an (incorrect) LP-model reading error, while with the previous release, the error was that the problem is infeasible (correct), c.f. screenshot:

![image](https://user-images.githubusercontent.com/16731716/169227308-48019883-f144-4bad-b1f1-48717813cc07.png)

By the way, not sure the problem is with the JavaScript wrapper, because I see there was an update of Highs version.

_Edit: I saw there were some changes in the parsing out HiGHS output as well (https://github.com/lovasoa/highs-js/commit/535a0d3df2981856599255e28f3793eb95702e8e), so, maybe one of these now incorrectly manage this infeasible problem._

Cheers,

Roman

**Comment by jajhall** [comment]
I'll look at this: there have been quite a few modifications to our .lp file reader in the past few weeks.

**Comment by jajhall** [comment]
`HiGHS::readModel(filename)` reads this problem, but returns a warning value of 1 due to the inconsistent bounds.

The value of HighsStatus::kWarning was changed a while ago - before v1.1.1 was created on 27/9/21 - so it's nothing new

**Comment by jajhall** [comment]
Sorry: hit close issue, rather than comment!

**Comment by lequant40** [comment]
Thanks @jajhall , so, it means this is a side effect of a change in the JavaScript wrapper then.

**Comment by fuglede** [comment]
What does `1 x0 1 x1 = 1` mean? `1 x0 + 1 x1 = 1` or something more like a quadratic constraint a la `[2 x0 x1]/2`?

**Comment by jajhall** [comment]
Well spotted. I guess it's interpreted as x0+x1 as HiGHS can't handle quadratic constraints

**Comment by lequant40** [comment]
Yep, interpreted as x0 + x1 indeed.

![image](https://user-images.githubusercontent.com/16731716/169595760-86aa6065-fd75-4d20-bbfb-7124980440f5.png)

**Comment by fuglede** [comment]
This is unrelated to changes in output parsing and happens already when loading the model; concretely, this happens because the C API function `readModel` returns a non-zero value (`HighsStatus::kWarning` as opposed to `HighsStatus::kOk`) where `highs-js` expects a 0 (cf. `assert_ok`). Removing this check yields a result whose `Status` is `'Infeasible'`.

**Comment by lequant40** [comment]
@fuglede , while I cannot comment more than this, my 2 cents if I may.

I interpret what @jajhall wrote as "no change in HiGHS output since Sep 2021".

I interpret what you wrote as "1) the problem is linked to HiGHS ouput, wrongly interpreted by high-js and 2) the problem is not linked to change in output parsing"

But then, why this sudden change of behaviour of high-js between highs-js 0.5.0 and 0.6.0?

![image](https://user-images.githubusercontent.com/16731716/169668336-333fff8e-6f5a-40bf-8b8e-0df65c7b8a20.png)
![image](https://user-images.githubusercontent.com/16731716/169668338-d072ca03-ce67-4c7f-9839-1c1a43ad97a1.png)

Cheers,

Roman

**Comment by jajhall** [comment]
The "pretty" output hasn't changed since Sept 2021, but it's just possible that the warning return when inconsistent bounds are specified is post Sept 2021. This could cause "this sudden change of behaviour of high-js between highs-js 0.5.0 and 0.6.0?"

**Comment by lequant40** [comment]
Thanks @jajhall.

Would it makes sense that such changes of behaviour of HiGHS be tracked in release notes, so that when integrating a new HiGHS version in high-js, integrators are aware of these changes and can cross-ref any issue with them?

_(And/or implementing regular/automated bump of HiGHS version to high-js, in the same spirit, to be able to kind of immediately detect changes upon integration of a new HiGHS version?)_

**Comment by jajhall** [comment]
We are starting to develop release notes, but can't track things at this level of detail. The short answer in this case is that, as with any HiGHS call, you need to consider a warning return as well as error.

**Comment by lequant40** [comment]
I guess this recommendation is matching was is being done through https://github.com/lovasoa/highs-js/pull/18, so, should be all good!

**Comment by jajhall** [comment]
> What does `1 x0 1 x1 = 1` mean? `1 x0 + 1 x1 = 1` or something more like a quadratic constraint a la `[2 x0 x1]/2`?

By the way, Gurobi throws up the following error if it's given the `.lp` file with this line

> Error reading LP format file ml.lp at line 5
> Malformed term in expression
> Neighboring tokens: " 1 x0 1 x1 = 1 Bounds 0 "

> Error 10012: Unable to read file

Although HiGHS currently reads it, I'd rather throw an error since the file reader is assuming a "+" symbol (and hence a linear constraint) when a user might think that he's defined a quadratic constraint or forgotten to put in the "-" sign when he wanted `x0 - x1 = 1`

**Comment by fuglede** [comment]
> Although HiGHS currently reads it, I'd rather throw an error 

I agree; since whitespace is generally disregarded completely in the format, I think the correct parsing (but likely always unintentional) here would be `1 x01x1 = 1`, cf. https://github.com/ERGO-Code/HiGHS/issues/851. From a quick look, the changes in https://github.com/ERGO-Code/HiGHS/pull/873 are not quite sufficient to cause it to throw an error here.

**Comment by jajhall** [comment]
Handling whitespace correctly in LP files is something that @feldmeier will work on, and we discussed spaces in variable names on Thursday. He's got other priorities, though.

I disagree about interpreting ` 1 x0 1 x1 = 1` as `1 x01x1 = 1`, since Gurobi considers it as an error.
