### ISSUE TITLE
Recompile with newer version of emscripten

### ISSUE THREAD

**Issue by RebeccaStevens** [lovasoa/highs-js#23]
Re #22 

The current release (0.7.3) on npm does not work on node 18 or 19. It does however work if I compile the code myself.

I believe that simply the version of emscripten that you are using to compile the code is out of date and needs to be updated to support newer versions of node.

**Comment by lovasoa** [comment]
Yes, that would be a good thing. PR welcome ! 

The files to update are https://github.com/lovasoa/highs-js/blob/main/.devcontainer/Dockerfile
https://github.com/lovasoa/highs-js/blob/main/.github/workflows/CI.yml
and
https://github.com/lovasoa/highs-js/blob/main/.github/workflows/release.yml
