### ISSUE TITLE
Release new package version

### ISSUE THREAD

**Issue by roessland** [lovasoa/highs-js#28]
Hi, I'm getting an error that looks like: `TypeError: Failed to parse URL ...` when importing highs 0.7.3 in a project that uses ESM.

It seems to work fine when I built the package myself however, so I guess this has been fixed on master but not yet pushed to the npm registry. Maybe related to emsdk version?

So it would be awesome 0.7.4 could be released.

Thanks for this package by the way 🙌

**Comment by mitschmidt** [comment]
Experiencing the same issue after upgrading node from 16 to 18.

**Comment by lovasoa** [comment]
v0.7.4 is being deployed: https://github.com/lovasoa/highs-js/actions/runs/5696720611/job/15442319767

**Comment by lovasoa** [comment]
https://www.npmjs.com/package/highs

**Comment by mitschmidt** [comment]
@lovasoa that was really fast - thank you for your efforts!
