### ISSUE TITLE
"Unable to read LP model" but HiGHS itself works

### ISSUE THREAD

**Issue by fuglede** [lovasoa/highs-js#34]
If I run [this model](https://github.com/lovasoa/highs-js/files/12843086/model.txt) through the demo website, I get a

> Error: Unable to read LP model (see http://web.mit.edu/lpsolve/doc/CPLEX-format.htm). HiGHS error 

yet HiGHS proper (tested with Running HiGHS 1.5.1 [date: 2023-04-19, git hash: be21711c9]) manages to read it just fine (after saving it with an `.lp` extension). Edit: Just tried with HiGHS 1.6.0 off of the current master, and that also works.

**Comment by jajhall** [comment]
Is this related to the example you've posted as part of a HiGHS issue?

**Comment by jajhall** [comment]
OK, thanks. For this issue, I don't know what's changed that might affect this model, but what version of HiGHS are you using?

**Comment by fuglede** [comment]
https://github.com/lovasoa/highs-js/ bundles [HiGHS @ 8194724](https://github.com/ERGO-Code/HiGHS/tree/81947249d6277525efc1690f60597b562670f28b), corresponding to HiGHS 1.2.2 [date: 2023-10-09, git hash: 81947249d]. I tried building the old version of HiGHS and found the same issue; it wouldn't read this particular `.lp`.

So, a submodule bump should do the job.

**Comment by jajhall** [comment]
That's a very out-of-date version of HiGHS! There have been many updates to the .LP file reader since then

**Comment by lovasoa** [comment]
Yes, we are stuck on an old version because the API did not expose everything we needed, so we resorted to parsing the text output, and its format changed.

**Comment by fuglede** [comment]
I can confirm that this is no longer an issue after the 1.0.0 `highs-js` update.
