### ISSUE TITLE
Possible to Update to HiGHS Version 1.7?

### ISSUE THREAD

**Issue by walaccio** [lovasoa/highs-js#39]
First of all, really nice project guys! I can imagine about a million use cases for this

Secondly somewhat selfishly, it would be great if this could be updated to the latest version of HiGHS- there have been some nice fixes across 1.7 & 1.71. It seems like I have a problem that is just too much for 1.6.... and unfortunately I have proven incompetent at building attempting the build to recreate the .wasm file myself. Would be greatly appreciated if that could be  updated

Huge thanks again for all the effort put into this!

**Comment by lovasoa** [comment]
You can open a PR where you update the HiGHS submodule in this repository. The build and tests will run on CI

**Comment by walaccio** [comment]
Ok, I'll give it a go- thanks
