### ISSUE TITLE
FS error thrown when solving several problems in the same process

### ISSUE THREAD

**Issue by lequant40** [lovasoa/highs-js#5]
Hello !

I would like to report a new issue, probably linked to the way the file system is used to communicate the model file or to get back the output.

Reproducer (in Node.js):

```
var model = `Minimize
obj: 0.03825456049385832 x0 0.02288637701933333 x1 0.02291198645458956 x2 0.02283623491294892 x3 0.041864094934297574 x4 0.022862749841213607 x5 0.022886319920344584 x6 0.022880713318479868 x7 0.022884457036775902 x8 0.01739177268113499 x9
Subject To
c1: 1 x0 1 x1 1 x2 1 x3 1 x4 1 x5 1 x6 1 x7 1 x8 1 x9 = 1
c2: -1 x0 -1 x1 -1 x2 -0.5 x3 0 x4 0 x5 0 x6 0 x7 0 x8 0 x9 <= -0.2
c3: 0 x0 0 x1 0 x2 0.5 x3 1 x4 1 x5 1 x6 0 x7 0 x8 0 x9 <= 0.5
Bounds
0.1 <= x0 <= 0.3
0 <= x1 <= 0.3
0 <= x2 <= 0.3
0 <= x3 <= 0.3
0.1 <= x4 <= 0.3
0 <= x5 <= 0.3
0 <= x6 <= 0.3
0 <= x7 <= 0.3
0 <= x8 <= 0.3
0 <= x9 <= 0.3
End`

const highs = await require("highs")();
var sol;
var count = 0;
var maxTries = 10000;
while(++count <= maxTries) {
    try {
      console.log(count)
      sol = highs.solve(model)
      
    } catch (e) {
        console.log(e);
        break;
    }
}
```

At a certain point, the following error is thrown:
```

...
4093
4094
4095 <--- Note: this is the count of the number of executions on my Node REPL
P [Error] <--- The failure
    at Ib (/node_modules/highs/build/highs.js:51:125)
    at /node_modules/highs/build/highs.js:63:426
    at REPL1:1:52
    at REPL1:2:4
    at Script.runInThisContext (vm.js:133:18)
    at REPLServer.defaultEval (repl.js:484:29)
    at bound (domain.js:413:15)
    at REPLServer.runBound [as eval] (domain.js:424:12)
    at REPLServer.onLine (repl.js:817:10)
    at REPLServer.emit (events.js:327:22) {
  node: undefined,
  Ja: [Function (anonymous)],
  Y: 33,
  message: 'FS error'
```

Please note that this error is not occuring in the Node.js REPL only, but in Node.js application as well (I did not try the browser).

Please also note that this reproducer is just here for illustration.
Real use-case, as per title, is to use HiGHS to solve several (different) problems. At some point, this error pops up.

I suspect that maybe there are too many file descriptors opened and maybe not cleaned (related to the _m.lp_ file usage) or too much data accumulated in stdout/stderr (_stderr_ seems to be used to read the results from HiGHS).

Maybe some clean-up would need to be done after each model solve ?

Cheers!

**Comment by lequant40** [comment]
Maybe unlinking would do the trick -> https://emscripten.org/docs/api_reference/Filesystem-API.html

From the example there:

```
FS.writeFile('/foobar.txt', 'Hello, world');
FS.unlink('/foobar.txt');
```

So, it seems an FS.unlink on the model file should be done at the end to prevent bad stuff.

Maybe a starting point ?

**Comment by lovasoa** [comment]
Hello, and thanks for the report ! 
To understand where it comes from, you can try to compile this library in debug mode (without the closure compiler, and with `-g` in `build.sh`).
There shouldn't be any file descriptor since we are working with a single file and constantly overwriting it.
However, we have a  memory leak in stdout_lines. We don't need to keep track of stdout at all, so we could just remove this array.

Are you interested in making a PR ?

**Comment by lequant40** [comment]
Looking at the FS code (https://github.com/emscripten-core/emscripten/blob/main/src/library_fs.js), there are 2 limitations at 4096 items:
- File descriptors (https://github.com/emscripten-core/emscripten/blob/main/src/library_fs.js#L395) 
- The table containing the hash of the files (https://github.com/emscripten-core/emscripten/blob/main/src/library_fs.js#L1455).

I think the problem comes from the second table: constantly "overwriting" the same file without unlinking it seems to be creating hashes in this table, which gets filled => error.

How could I build this project locally to try to add the FS.unlink ?
_**(With docker, if possible)**_

Re the stdout, I am not sure to understand.
Do you mean that this code (https://github.com/lovasoa/highs-js/blob/main/src/pre.js#L4) is not needed because the output of HiGHS is captured from stderr, but keeps growing nevertheless because HiGHS outputs something in stdout ?

**Comment by lequant40** [comment]
I confirm the problem also occurs in the browser (tested under Chrome).

**Comment by jajhall** [comment]
My understanding is that there's not an issue with HiGHS itself, but please let me know if there is.

**Comment by lequant40** [comment]
I found the issue.

While I do not understand it (it is linked to both the Emscripten File System API and to how the HiGHS function `Highs_writeSolutionPretty` interacts with it, and I have no interest in digging into the details), I do have a fix which consists in not using `stderr `to retrieve the results from HiGHS but using `stdout` (not providing an output file name to `Highs_writeSolutionPretty` makes it outputs the results on stdout).

@lovasoa, I'll do a PR later.

**Comment by lovasoa** [comment]
Great, thanks @lequant40 !

**Comment by lequant40** [comment]
PR done.

**Comment by lequant40** [comment]
I confirm v0.3.0 is working for this issue.

**Comment by lequant40** [comment]
@jajhall , indeed, there is an issue on HiGHS side, I found the root cause of the current error -> https://github.com/ERGO-Code/HiGHS/issues/512

**Comment by lovasoa** [comment]
Thank you @lequant40 for the investigation!

**Comment by jajhall** [comment]
Fixed in HiGHS
