### ISSUE TITLE
Version to solve MIPs?

### ISSUE THREAD

**Issue by jajhall** [lovasoa/highs-js#7]
I've been contacted by a user who has tried to solve a MIP with HiGHS JS version 0.3.0, but only the LP solution has been returned. Not a problem, since 
https://www.npmjs.com/package/highs
states, "This is a javascript linear programming library". 

However, now that the latest version of HiGHS can read MIPs as .lp files (and there's also no longer an finite restriction on line length) is it just a question of updating the version of HiGHS used by HiGHS JS to enable it to solve MIPs? 

Work, I know, but a valuable extension that's already got one potential user!

**Comment by lovasoa** [comment]
Yes, it should be as easy as updating the git submodule. Interested in making a PR ?

**Comment by jajhall** [comment]
I don't know how to formulate a PR to update HiGHS on in highs-js, although I see that you have some sort of link to a commit of HiGHS. You can replace this with the current master (b66030b). There have been vast changes to HiGHS since May, some in the API (sorry), so debugging may be needed. In particular, the dual values for constraints are now returned with opposite sign.

The compensation is not just a MIP solver, but the fastest open source MIP solver in the world

**Comment by lovasoa** [comment]
Ok. Is there a CHANGELOG with a documentation of the API changes ?

**Comment by lovasoa** [comment]
The list of functions used in highs-js is here, I need at least a documentation of all the changes affecting these functions to make the migration: https://github.com/lovasoa/highs-js/blob/main/build/exported_functions.json

**Comment by lovasoa** [comment]
For instance, it looks like Highs_modelStatusToChar, which this library uses, was deleted

**Comment by jajhall** [comment]
> Ok. Is there a CHANGELOG with a documentation of the API changes ?

Sorry, no. I started to prepare a document, but then work to develop the MIP solver took over.

**Comment by jajhall** [comment]
> The list of functions used in highs-js is here, I need at least a documentation of all the changes affecting these functions to make the migration: https://github.com/lovasoa/highs-js/blob/main/build/exported_functions.json

Thanks, I'll review these and give you the information that you need

**Comment by jajhall** [comment]
> For instance, it looks like Highs_modelStatusToChar, which this library uses, was deleted

Indeed, it didn't work on at least one platform

**Comment by lovasoa** [comment]
Also, maybe someone could work on https://github.com/ERGO-Code/HiGHS/issues/585 ? Without that, it's hard to make sure any use of the library is correct...

**Comment by jajhall** [comment]
> Also, maybe someone could work on [ERGO-Code/HiGHS#585](https://github.com/ERGO-Code/HiGHS/issues/585) ? Without that, it's hard to make sure any use of the library is correct...

Sure: Gurobi writes to console and a file by default, which seemed to be a reasonable mode.

**Comment by lovasoa** [comment]
@jajhall : So, can you update https://www.maths.ed.ac.uk/hall/HiGHS/HighsOptions.html ?

**Comment by lovasoa** [comment]
I published an updated highs-js to npm, with my guesses of what should be updated

**Comment by jajhall** [comment]
Thanks. I've tested 0.4.0 with a MIP, and it's being communicated to HiGHS OK, but the results are not being parsed correctly. This is because you're parsing the "pretty" solution file that, for MIPs has no status or dual values, since a MIP has only a primal solution: no optimal basis or dual solution. Hence you're quoting the "lower" value as the "status", the "upper" value as "lower",  "primal" as "upper" (which is how I know that the problem is being solved OK) and "primal" and "dual" are NaN since they are parsing the type name "Integer" and column name (eg) "x1" 

We've got a "raw" solution file format that should be much easier to parse. I'll send you details as well as updating
https://www.maths.ed.ac.uk/hall/HiGHS/HighsOptions.html

I've tested with an LP and note that the row duals are being identified correctly

**Comment by jajhall** [comment]
I've updated
https://www.maths.ed.ac.uk/hall/HiGHS/HighsOptions.html
and refreshed the rest of the documentation available there

**Comment by jajhall** [comment]
For the MIP problem file 
[DistillationMIP.lp.txt](https://github.com/lovasoa/highs-js/files/7558767/DistillationMIP.lp.txt)
here is the HiGHS solution file 
[Distillation.sol.txt](https://github.com/lovasoa/highs-js/files/7558770/Distillation.sol.txt)
if it's solved as an LP by deleting the following lines
General
x1 x2
If it's solved as a MIP, the solution file is 
[DistillationMIP.sol.txt](https://github.com/lovasoa/highs-js/files/7558774/DistillationMIP.sol.txt)
Hopefully it's straightforward in JavaScript to identify the primal solution, dual solution and basis (where 0 is basic, 1 is "at lower (LB)" and 2 is "at upper (UB)") and, the absence of the dual solution and basis in the case of MIP problems.

**Comment by lovasoa** [comment]
@jajhall : It looks like the "raw" format contains less information than the "pretty" one. I can't find the variable bounds in it, for instance. And I don't see myself re-parsing the input to extract that information.

**Comment by jajhall** [comment]
The variable bounds and integrally are part of the problem data, not the solution. 

The alternative is to parse the pretty format, but conditional on whether the problem is an LP or MIP

**Comment by lovasoa** [comment]
> The variable bounds and integrally are part of the problem data, not the solution.

Yes, but I don't feel like re-parsing the problem in js just to extract that information. 

> The alternative is to parse the pretty format, but conditional on whether the problem is an LP or MIP

I implemented that.

https://github.com/lovasoa/highs-js/blob/main/src/post.js#L126-L129

It's a little bit dirty, but it works :smiley:

**Comment by jajhall** [comment]
Great! That's good for us, too. The demo needs updating to 4.0.1

**Comment by lovasoa** [comment]
the demo is always automatically updated to the latest version :)

https://lovasoa.github.io/highs-js/

**Comment by jajhall** [comment]
OK. Must be a Firefox cache issue, then. Thanks

**Comment by jajhall** [comment]
Are you sure? I've just opened https://lovasoa.github.io/highs-js/ on my Windows laptop - rather than the Linux machine that I do my coding on - and I get v0.4.0 in both Chrome and Edge (that I otherwise never use).

**Comment by lovasoa** [comment]
Nope, it's 0.4.1. You can try putting a MIP in the demo, it works :)

![image](https://user-images.githubusercontent.com/552629/142951110-1173fb52-3e0a-419b-823e-8756da1ed80c.png)

**Comment by jajhall** [comment]
Indeed, I'm now getting 0.4.1. However,  for

Minimize
 obj: 8 x1 + 10 x2
Subject To
 c1: 2 x1 + 2 x2 >= 7
 c2: 3 x1 + 4 x2 >= 12
 c3: 2 x1 +   x2 >= 6
General
x1 x2
End

the row report is not correct
![image](https://user-images.githubusercontent.com/22636003/143024782-556e719c-8e89-4bb8-8949-90bc7efb153c.png)
The status should not be given, and the values that are quoted as "status" are the "primal" values.

**Comment by lovasoa** [comment]
It's highs itself that reports the row values as "status". This lib just converts it to json.

**Comment by lovasoa** [comment]
You are right, sorry ! This needs fixing.

**Comment by lovasoa** [comment]
It's fixed. Now there is a fast and easy to use MIP solver in js :)
